common:
  - { artifactId : hec-monolith, group: "mil.army.usace.hec", version : 3.3.27, source : "nexus"}
  - { artifactId : hec-monolith-compat, group: "mil.army.usace.hec", version : 3.3.27, source : "nexus" }
  - { artifactId : hec-nucleus-data, group: "mil.army.usace.hec", version : 2.0.1, source : "nexus" }
  - { artifactId : hec-nucleus-metadata, group: "mil.army.usace.hec", version : 2.0.1, source : "nexus" }
  - { artifactId : hecnf, group: "mil.army.usace.hec.hecnf", version : 7.2.0, source : "nexus" }
  - { artifactId : flogger, version : 0.5.1, source : "maven" }
  - { artifactId : flogger-system-backend, version : 0.5.1, source : "maven" }
windows:
  - { artifactId : javaHeclib, group: "mil.army.usace.hec", version : 7-IU-8-win-x86_64, maven.extension : "zip", source : "nexus" }
linux:
  - { artifactId : javaHeclib, group: "mil.army.usace.hec", version : 7-IU-8-linux-x86_64, maven.extension : "zip", source : "nexus" }
darwin: # OSX
  - { artifactId : javaHeclib, group: "mil.army.usace.hec", version : 7-IU-8-macOS-x86_64, maven.extension : "zip", source : "nexus" }
