# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
#          - {os: macos-latest,   r: 'release'}
#          - {os: windows-latest, r: 'release'}
#          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
#          - {os: ubuntu-latest,   r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

#      - uses: r-lib/actions/setup-pandoc@v2
#
#      - uses: r-lib/actions/setup-r@v2
#        with:
#          r-version: ${{ matrix.config.r }}
#          http-user-agent: ${{ matrix.config.http-user-agent }}
#          use-public-rspm: true
#
#      - uses: r-lib/actions/setup-r-dependencies@v2
#        with:
#          extra-packages: any::rcmdcheck
#          needs: check
      
      - uses: stCarolas/setup-maven@v4.5

      - uses: s4u/maven-settings-action@v2.8.0

      - name: download dependencies
        run: |
          echo ::group::Download flogger
          mvn -Dmaven.repo.local='${{ runner.temp }}/temp_repo' dependency:get -Dartifact='com.google.flogger:flogger-system-backend:0.7.4:jar'
          mvn -Dmaven.repo.local='${{ runner.temp }}/temp_repo' dependency:get -Dartifact='com.google.flogger:flogger:0.7.4:jar'
          echo ::endgroup::
          echo ::group::Download HEC Monolith
          mvn -Dmaven.repo.local='${{ runner.temp }}/temp_repo' dependency:get -Dartifact='mil.army.usace.hec:hec-monolith-compat:3.3.16:jar' -DremoteRepositories='https://www.hec.usace.army.mil/nexus/repository/maven-releases'
          mvn -Dmaven.repo.local='${{ runner.temp }}/temp_repo' dependency:get -Dartifact='mil.army.usace.hec:hec-monolith:3.3.16:jar' -DremoteRepositories='https://www.hec.usace.army.mil/nexus/repository/maven-releases'
          echo ::endgroup::
          echo ::group::Download HEC Nucleus
          mvn -Dmaven.repo.local='${{ runner.temp }}/temp_repo' dependency:get -Dartifact='mil.army.usace.hec:hec-nucleus-metadata:2.0.1:jar' -DremoteRepositories='https://www.hec.usace.army.mil/nexus/repository/maven-releases'
          echo ::endgroup::
          echo ::group::Download hecnf
          mvn -Dmaven.repo.local='${{ runner.temp }}/temp_repo' dependency:get -Dartifact='mil.army.usace.hec:hecnf:6.0.00.100:jar' -DremoteRepositories='https://www.hec.usace.army.mil/nexus/repository/maven-releases'
          echo ::endgroup::
          echo ::group::Download javaHeclib
          mvn -Dmaven.repo.local='${{ runner.temp }}/temp_repo' dependency:get -Dartifact='mil.army.usace.hec:javaHeclib:7-IQ-11-linux-x86_64:zip' -DremoteRepositories='https://www.hec.usace.army.mil/nexus/repository/maven-releases'
          echo ::endgroup::
          echo ::group::Copy dependencies to directory
          mkdir -p ${{ runner.temp }}/.dssrip2/jar ${{ runner.temp }}/.dssrip2/lib
          cp \
            ${{ runner.temp }}/temp_repo/mil/army/usace/hec/hec-nucleus-metadata/2.0.1/hec-nucleus-metadata-2.0.1.jar \
            ${{ runner.temp }}/temp_repo/mil/army/usace/hec/hec-monolith-compat/3.3.16/hec-monolith-compat-3.3.16.jar \
            ${{ runner.temp }}/temp_repo/mil/army/usace/hec/hec-monolith/3.3.16/hec-monolith-3.3.16.jar \
            ${{ runner.temp }}/temp_repo/com/google/flogger/flogger-system-backend/0.7.4/flogger-system-backend-0.7.4.jar \
            ${{ runner.temp }}/temp_repo/com/google/flogger/flogger/0.7.4/flogger-0.7.4.jar \
            ${{ runner.temp }}/temp_repo/mil/army/usace/hec/hecnf/6.0.00.100/hecnf-6.0.00.100.jar \
            ${{ runner.temp }}/.dssrip2/jar
          7z e ${{ runner.temp }}/temp_repo/mil/army/usace/hec/javaHeclib/7-IQ-11-linux-x86_64/javaHeclib-7-IQ-11-linux-x86_64.zip \
            -o${{ runner.temp }}/.dssrip2/lib
          echo "DSS_HOME_CI=${{ runner.temp }}/.dssrip2" >> $GITHUB_ENV        
          echo ::endgroup::
  
      - name: check stuff
        run: |
          find $DSS_HOME_CI/jar -type f -printf "%h/%f \n"
          find $DSS_HOME_CI/lib -type f -printf "%h/%f \n"

#      - uses: r-lib/actions/check-r-package@v2
#        with:
#          upload-snapshots: true
  