# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
      
      - uses: clausnz/github-action-download-maven-artifact@master
        id: download-maven-artifact
        with:
          groupId: com.google.flogger
          artifactId: flogger-system-backend
          version: 0.7.4
          extension: jar
          repository: maven2
          url: https://repo.maven.org/maven2/

      - name: Output file path in container
        run: |
          echo "File has been downloaded to ${{ steps.download-maven-artifact.outputs.file }}"

      - uses: clausnz/github-action-download-maven-artifact@master
        with:
          groupId: com.google.flogger
          artifactId: flogger
          version: 0.7.4
          extension: jar
          repository: maven2
          url: https://repo.maven.org/maven2/
          outputDirectory: home/.dssrip2/monolith/jar

      - uses: clausnz/github-action-download-maven-artifact@master
        with:
          groupId: mil.army.usace.hec
          artifactId: hec-monolith-compat
          version: 3.3.16
          extension: jar
          repository: nexus
          url:  https://www.hec.usace.army.mil/nexus/repository/maven-releases/
          outputDirectory: home/.dssrip2/monolith/jar

      - uses: clausnz/github-action-download-maven-artifact@master
        with:
          groupId: mil.army.usace.hec
          artifactId: hec-monolith
          version: 3.3.16
          extension: jar
          repository: nexus
          url:  https://www.hec.usace.army.mil/nexus/repository/maven-releases/
          outputDirectory: home/.dssrip2/monolith/jar

      - uses: clausnz/github-action-download-maven-artifact@master
        with:
          groupId: mil.army.usace.hec
          artifactId: hec-nucleus-metadata
          version: 2.0.1
          extension: jar
          repository: nexus
          url:  https://www.hec.usace.army.mil/nexus/repository/maven-releases/
          outputDirectory: home/.dssrip2/monolith/jar

      - uses: clausnz/github-action-download-maven-artifact@master
        with:
          groupId: mil.army.usace.hec
          artifactId: hecnf
          version: 6.0.00.100
          extension: jar
          repository: nexus
          url:  https://www.hec.usace.army.mil/nexus/repository/maven-releases/
          outputDirectory: home/.dssrip2/monolith/jar

      - uses: clausnz/github-action-download-maven-artifact@master
        with:
          groupId: mil.army.usace.hec
          artifactId: javaHeclib
          version: 7-IQ-11-linux-x86_64
          extension: zip
          repository: nexus
          url:  https://www.hec.usace.army.mil/nexus/repository/maven-releases/
          outputDirectory: home/.dssrip2/monolith/lib

      - uses: ihiroky/extract-action@v1
        with:
          file_path: home/.dssrip2/monolith/lib/javaHeclib-7-IQ-11-linux-x86_64.zip
          extract_dir: home/.dssrip2/monolith/lib

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
